In [2]:
# MEDIAN HOME VALUE DATA - Alanis Perez

In [4]:
import pandas as pd

In [6]:
# Read CSV files
# Median Homevalue
home_data_path = "data/avg_cost_by_county.csv"
home_data = pd.read_csv(home_data_path)

In [8]:
# Filter home data to CA only
home_df = home_data[home_data['State'] == 'CA']
home_df.head()

,RegionID,SizeRank,RegionName,State,1/31/2004,2/29/2004,3/31/2004,4/30/2004,5/31/2004,6/30/2004,...,10/31/2023,11/30/2023,12/31/2023,1/31/2024,2/29/2024,3/31/2024,4/30/2024,5/31/2024,6/30/2024,7/31/2024
0,3101,0,Los Angeles County,CA,359637.887854,365587.644879,371964.449058,379899.180522,389740.328886,399902.550401,...,8.699550e+05,8.780677e+05,8.830974e+05,8.820560e+05,8.771504e+05,8.732556e+05,8.739083e+05,8.771538e+05,8.792955e+05,8.830360e+05
4,2841,4,San Diego County,CA,398657.715678,404627.790326,413281.930706,421490.824884,429782.054434,442327.588370,...,9.025327e+05,9.090164e+05,9.124351e+05,9.147283e+05,9.193116e+05,9.276140e+05,9.379771e+05,9.468492e+05,9.513943e+05,9.528563e+05
5,1286,5,Orange County,CA,458896.266885,468073.348388,481813.802378,495424.699157,510176.798158,525516.743374,...,1.084817e+06,1.096047e+06,1.103526e+06,1.107221e+06,1.109519e+06,1.116254e+06,1.128691e+06,1.143474e+06,1.153868e+06,1.161599e+06
9,2832,9,Riverside County,CA,256206.928900,259733.009456,264097.815811,269462.124990,275191.182200,282795.503609,...,5.904493e+05,5.930607e+05,5.953860e+05,5.973129e+05,5.994030e+05,6.020490e+05,6.049911e+05,6.079180e+05,6.096283e+05,6.110266e+05
13,3250,13,San Bernardino County,CA,212230.989893,216081.062886,220643.904351,225634.413575,230739.620461,235869.558118,...,5.345444e+05,5.392195e+05,5.435988e+05,5.457050e+05,5.461188e+05,5.461116e+05,5.470725e+05,5.492992e+05,5.511573e+05,5.529189e+05

In [16]:
home_df.head()

,RegionID,SizeRank,RegionName,State,1/31/2004,2/29/2004,3/31/2004,4/30/2004,5/31/2004,6/30/2004,...,10/31/2023,11/30/2023,12/31/2023,1/31/2024,2/29/2024,3/31/2024,4/30/2024,5/31/2024,6/30/2024,7/31/2024
0,3101,0,Los Angeles County,CA,359637.887854,365587.644879,371964.449058,379899.180522,389740.328886,399902.550401,...,8.699550e+05,8.780677e+05,8.830974e+05,8.820560e+05,8.771504e+05,8.732556e+05,8.739083e+05,8.771538e+05,8.792955e+05,8.830360e+05
4,2841,4,San Diego County,CA,398657.715678,404627.790326,413281.930706,421490.824884,429782.054434,442327.588370,...,9.025327e+05,9.090164e+05,9.124351e+05,9.147283e+05,9.193116e+05,9.276140e+05,9.379771e+05,9.468492e+05,9.513943e+05,9.528563e+05
5,1286,5,Orange County,CA,458896.266885,468073.348388,481813.802378,495424.699157,510176.798158,525516.743374,...,1.084817e+06,1.096047e+06,1.103526e+06,1.107221e+06,1.109519e+06,1.116254e+06,1.128691e+06,1.143474e+06,1.153868e+06,1.161599e+06
9,2832,9,Riverside County,CA,256206.928900,259733.009456,264097.815811,269462.124990,275191.182200,282795.503609,...,5.904493e+05,5.930607e+05,5.953860e+05,5.973129e+05,5.994030e+05,6.020490e+05,6.049911e+05,6.079180e+05,6.096283e+05,6.110266e+05
13,3250,13,San Bernardino County,CA,212230.989893,216081.062886,220643.904351,225634.413575,230739.620461,235869.558118,...,5.345444e+05,5.392195e+05,5.435988e+05,5.457050e+05,5.461188e+05,5.461116e+05,5.470725e+05,5.492992e+05,5.511573e+05,5.529189e+05