In [1]:
import pandas as pd

# Load the .xls Excel file
KernCounty = pd.read_excel("Resources/BAKE$HWS.xls", engine='xlrd')

# Display the first few rows of the DataFrame
print (KernCounty)

    SORTORDER  BMYEAR   AREA                        INCLUDES  BREAKS  PNCO  \
0           1    2023  12540                             NaN     NaN     1
1           2    2023  12540                             NaN     NaN     1
2           3    2023  12540                             NaN     NaN     1
3           4    2023  12540                             NaN     NaN     1
4           8    2023  12540           110000-813000, 920000     NaN     1
5           9    2023  12540    111000-113200, 114000-115000     NaN     1
6          10    2023  12540    113000, 210000-813000, 92000     NaN     1
7          11    2023  12540           113000, 210000-813000     NaN     1
8          12    2023  12540                             NaN     NaN     1
9          13    2023  12540              10000000, 20000000     NaN     1
10         14    2023  12540                 1133000, 210000     NaN     1
11         15    2023  12540                             NaN     NaN     1
12         16    2023  12540                   310000-330000     NaN     1
13         17    2023  12540           321000, 327000-330000     NaN     1
14         18    2023  12540    311000-316000, 322000-326000     NaN     1
15         19    2023  12540                             NaN     NaN     1
16         21    2023  12540    220000, 420000-813000, 92000     NaN     1
17         22    2023  12540                             NaN     NaN     1
18         23    2023  12540           220000, 420000-490000     NaN     1
19         24    2023  12540                             NaN     NaN     1
20         25    2023  12540                             NaN     NaN     1
21         26    2023  12540                             NaN     NaN     1
22         27    2023  12540                             NaN     NaN     1
23         28    2023  12540                             NaN     NaN     1
24         29    2023  12540                             NaN     NaN     1
25         31    2023  12540                             NaN     NaN     1
26         32    2023  12540                             NaN     NaN     1
27         33    2023  12540                   520000-530000     NaN     1
28         34    2023  12540                             NaN     NaN     1
29         35    2023  12540                             NaN     NaN     1
30         36    2023  12540                   540000-560000     NaN     1
31         37    2023  12540                             NaN     NaN     1
32         38    2023  12540                             NaN     NaN     1
33         39    2023  12540                             NaN     NaN     1
34         40    2023  12540                   610000-620000     NaN     1
35         41    2023  12540                             NaN     NaN     1
36         42    2023  12540                             NaN     NaN     1
37         43    2023  12540                             NaN     NaN     1
38         44    2023  12540                             NaN     NaN     1
39         46    2023  12540                   710000-720000     NaN     1
40         47    2023  12540                             NaN     NaN     1
41         48    2023  12540                             NaN     NaN     1
42         50    2023  12540                             NaN     NaN     1
43         51    2023  12540                  722511, 722590     NaN     1
44         53    2023  12540                   811000-813000     NaN     1
45         54    2023  12540  910000, 920000, 930000, 940000     NaN     1
46         55    2023  12540                   910000-912999     NaN     1
47         56    2023  12540                             NaN     NaN     1
48         57    2023  12540                             NaN     NaN     1
49         58    2023  12540                  920000, 930000     NaN     1
50         59    2023  12540                  921611, 922999     NaN     1
51         60    2023  12540                             NaN     NaN     1
52         61    2023  12540                             NaN     NaN     1
53         62    2023  12540  931611, 939012, 939022, 932994     NaN     1
54         63    2023  12540                             NaN     NaN     1
55         64    2023  12540                             NaN     NaN     1
56         65    2023  12540                             NaN     NaN     1
57         66    2023  12540                             NaN     NaN     1
58         67    2023  12540                  931150, 939032     NaN     1

     SS-NAICS                                              TITLE  \
0   00-000010                               Civilian Labor Force
1   00-000020                                Civilian Employment
2   00-000030                              Civilian Unemployment
3   00-000040                         Civilian Unemployment Rate
4   01-000000                              Total, All Industries
5   11-000000                                         Total Farm
6   00-000000                                      Total Nonfarm
7   05-000000                                      Total Private
8   06-000000                                    Goods Producing
9   15-000000                  Mining, Logging, and Construction
10  10-000000                                 Mining and Logging
11  20-000000                                       Construction
12  30-000000                                      Manufacturing
13  31-000000                                      Durable Goods
14  32-000000                                  Non-Durable Goods
15  32-311000                                 Food Manufacturing
16  07-000000                                  Service-Providing
17  08-000000                          Private Service Providing
18  40-000000               Trade, Transportation, and Utilities
19  41-000000                                    Wholesale Trade
20  42-000000                                       Retail Trade
21  42-445000                        Food and Beverage Retailers
22  42-455000                      General Merchandise Retailers
23  42-455100                                  Department Stores
24  42-458000            Clothing, Clothing Accessories, Shoe...
25  43-000000          Transportation, Warehousing, and Utili...
26  50-000000                                        Information
27  55-000000                               Financial Activities
28  55-520000                              Finance and Insurance
29  55-530000                 Real Estate and Rental and Leasing
30  60-000000                 Professional and Business Services
31  60-540000          Professional, Scientific, and Technica...
32  60-550000            Management of Companies and Enterprises
33  60-560000          Administrative and Support and Waste a...
34  65-000000              Private Education and Health Services
35  65-610000                       Private Educational Services
36  65-620000                  Health Care and Social Assistance
37  65-621000                    Ambulatory Health Care Services
38  65-622000                                          Hospitals
39  70-000000                            Leisure and Hospitality
40  70-710000                Arts, Entertainment, and Recreation
41  70-720000                    Accommodation and Food Services
42  70-722000                  Food Services and Drinking Places
43  70-722500                Restaurants and Other Eating Places
44  80-000000                                     Other Services
45  90-000000                                         Government
46  90-910000                                 Federal Government
47  90-919110                              Department of Defense
48  90-912991            Federal Government excluding Departm...
49  90-940000                   Total State and Local Government
50  90-920000                                   State Government
51  90-921611              State Government Educational Services
52  90-922000               State Government Excluding Education
53  90-930000                                   Local Government
54  90-931611              Local Government Educational Services
55  90-932000          Local Government excluding Educational...
56  90-939012                                  County Government
57  90-939022                                    City Government
58  90-932994                      Special Districts plus Tribes

    2010-01-01 00:00:00  2010-02-01 00:00:00  ...  2023-10-01 00:00:00  \
0            368200.000           367500.000  ...           398200.000
1            304900.000           302400.000  ...           367000.000
2             63300.000            65100.000  ...            31200.000
3                 0.172                0.177  ...                0.078
4            263700.000           260600.000  ...           358700.000
5             38000.000            34800.000  ...            65200.000
6            225700.000           225800.000  ...           293500.000
7            165500.000           164900.000  ...           222200.000
8             34000.000            33400.000  ...            36500.000
9             21300.000            20800.000  ...            23900.000
10             9100.000             8700.000  ...             7600.000
11            12200.000            12100.000  ...            16300.000
12            12700.000            12600.000  ...            12600.000
13             5000.000             5000.000  ...             5000.000
14             7700.000             7600.000  ...             7600.000
15             5400.000             5400.000  ...             4600.000
16           191700.000           192400.000  ...           257000.000
17           131500.000           131500.000  ...           185700.000
18            41700.000            41500.000  ...            61900.000
19             7000.000             6900.000  ...             8300.000
20            26000.000            25900.000  ...            32700.000
21             5500.000             5500.000  ...             7000.000
22             5600.000             5600.000  ...             7700.000
23             2500.000             2300.000  ...             1700.000
24             2200.000             2100.000  ...             2300.000
25             8700.000             8700.000  ...            20900.000
26             2700.000             2600.000  ...             1700.000
27             7800.000             7900.000  ...             7600.000
28             4800.000             4800.000  ...             4100.000
29             3000.000             3100.000  ...             3500.000
30            23700.000            23400.000  ...            27400.000
31            10200.000            10100.000  ...            11400.000
32             2900.000             2800.000  ...             2700.000
33            10600.000            10500.000  ...            13300.000
34            29200.000            29300.000  ...            48300.000
35             1700.000             1800.000  ...             2100.000
36            27500.000            27500.000  ...            46200.000
37            10400.000            10400.000  ...            16700.000
38             6300.000             6300.000  ...             8100.000
39            19800.000            20100.000  ...            29700.000
40             2200.000             2300.000  ...             2600.000
41            17600.000            17800.000  ...            27100.000
42            15900.000            16100.000  ...            25200.000
43            15400.000            15600.000  ...            24300.000
44             6600.000             6700.000  ...             9100.000
45            60200.000            60900.000  ...            71300.000
46            10500.000            10500.000  ...            11100.000
47             7600.000             7600.000  ...             8300.000
48             2900.000             2900.000  ...             2800.000
49            49700.000            50400.000  ...            60200.000
50             9800.000             9900.000  ...             9600.000
51             1200.000             1300.000  ...             1800.000
52             8600.000             8600.000  ...             7800.000
53            39900.000            40500.000  ...            50600.000
54            25500.000            26200.000  ...            34200.000
55            14400.000            14300.000  ...            16400.000
56             9600.000             9600.000  ...            11100.000
57             2600.000             2500.000  ...             3000.000
58             2200.000             2300.000  ...             2300.000

    2023-11-01 00:00:00  2023-12-01 00:00:00  2024-01-01 00:00:00  \
0            400100.000           395400.000           399100.000
1            368400.000           361100.000           361100.000
2             31700.000            34300.000            38000.000
3                 0.079                0.087                0.095
4            359200.000           353000.000           345400.000
5             64100.000            56200.000            54800.000
6            295100.000           296800.000           290600.000
7            222700.000           223400.000           219200.000
8             36300.000            36400.000            35800.000
9             23800.000            23900.000            23300.000
10             7600.000             7600.000             7600.000
11            16200.000            16300.000            15700.000
12            12500.000            12500.000            12500.000
13             5000.000             5000.000             5000.000
14             7500.000             7500.000             7500.000
15             4600.000             4600.000             4700.000
16           258800.000           260400.000           254800.000
17           186400.000           187000.000           183400.000
18            62500.000            62800.000            60300.000
19             8300.000             8300.000             8300.000
20            33200.000            33500.000            31700.000
21             7100.000             7000.000             6900.000
22             7900.000             8000.000             7300.000
23             1800.000             1800.000             1500.000
24             2500.000             2600.000             2200.000
25            21000.000            21000.000            20300.000
26             1700.000             1700.000             1700.000
27             7600.000             7600.000             7600.000
28             4100.000             4100.000             4100.000
29             3500.000             3500.000             3500.000
30            27400.000            27500.000            27200.000
31            11400.000            11700.000            11700.000
32             2800.000             2800.000             2700.000
33            13200.000            13000.000            12800.000
34            48500.000            48800.000            48700.000
35             2200.000             2200.000             2100.000
36            46300.000            46600.000            46600.000
37            16700.000            16800.000            16700.000
38             8200.000             8200.000             8200.000
39            29700.000            29600.000            29000.000
40             2600.000             2600.000             2600.000
41            27100.000            27000.000            26400.000
42            25200.000            25000.000            24500.000
43            24400.000            24100.000            23600.000
44             9000.000             9000.000             8900.000
45            72400.000            73400.000            71400.000
46            11100.000            11200.000            11100.000
47             8300.000             8300.000             8400.000
48             2800.000             2900.000             2700.000
49            61300.000            62200.000            60300.000
50             9600.000             9500.000             9500.000
51             1800.000             1800.000             1800.000
52             7800.000             7700.000             7700.000
53            51700.000            52700.000            50800.000
54            35600.000            36600.000            34800.000
55            16100.000            16100.000            16000.000
56            10900.000            10800.000            10600.000
57             3000.000             3100.000             3100.000
58             2200.000             2200.000             2300.000

    2024-02-01 00:00:00  2024-03-01 00:00:00  2024-04-01 00:00:00  \
0            400100.000           391900.000           388500.000
1            358600.000           352000.000           351600.000
2             41500.000            39900.000            37000.000
3                 0.104                0.102                0.095
4            344000.000           335700.000           339700.000
5             53100.000            43800.000            46800.000
6            290900.000           291900.000           292900.000
7            218700.000           219200.000           219800.000
8             35500.000            35700.000            35800.000
9             23100.000            23300.000            23400.000
10             7600.000             7600.000             7600.000
11            15500.000            15700.000            15800.000
12            12400.000            12400.000            12400.000
13             5000.000             5000.000             5000.000
14             7400.000             7400.000             7400.000
15             4600.000             4600.000             4600.000
16           255400.000           256200.000           257100.000
17           183200.000           183500.000           184000.000
18            59800.000            59700.000            59900.000
19             8300.000             8200.000             8300.000
20            31400.000            31500.000            31600.000
21             6900.000             6800.000             6800.000
22             7200.000             7200.000             7200.000
23             1500.000             1400.000             1400.000
24             2100.000             2100.000             2100.000
25            20100.000            20000.000            20000.000
26             1700.000             1700.000             1700.000
27             7600.000             7400.000             7500.000
28             4100.000             4000.000             4100.000
29             3500.000             3400.000             3400.000
30            27400.000            27500.000            27600.000
31            11900.000            11800.000            11900.000
32             2700.000             2700.000             2700.000
33            12800.000            13000.000            13000.000
34            48600.000            49000.000            48800.000
35             2200.000             2200.000             2200.000
36            46400.000            46800.000            46600.000
37            16800.000            16900.000            16800.000
38             8200.000             8300.000             8300.000
39            29100.000            29200.000            29400.000
40             2600.000             2700.000             2700.000
41            26500.000            26500.000            26700.000
42            24600.000            24500.000            24700.000
43            23800.000            23700.000            23900.000
44             9000.000             9000.000             9100.000
45            72200.000            72700.000            73100.000
46            11100.000            11100.000            11100.000
47             8300.000             8300.000             8300.000
48             2800.000             2800.000             2800.000

In [2]:
KernCounty.head()

,SORTORDER,BMYEAR,AREA,INCLUDES,BREAKS,PNCO,SS-NAICS,TITLE,2010-01-01 00:00:00,2010-02-01 00:00:00,...,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00
0,1,2023,12540,NaN,NaN,1,00-000010,Civilian Labor Force,368200.000,367500.000,...,398200.000,400100.000,395400.000,399100.000,400100.000,391900.000,388500.000,391500.000,390400.00,391700.000
1,2,2023,12540,NaN,NaN,1,00-000020,Civilian Employment,304900.000,302400.000,...,367000.000,368400.000,361100.000,361100.000,358600.000,352000.000,351600.000,359000.000,355100.00,354700.000
2,3,2023,12540,NaN,NaN,1,00-000030,Civilian Unemployment,63300.000,65100.000,...,31200.000,31700.000,34300.000,38000.000,41500.000,39900.000,37000.000,32500.000,35300.00,37100.000
3,4,2023,12540,NaN,NaN,1,00-000040,Civilian Unemployment Rate,0.172,0.177,...,0.078,0.079,0.087,0.095,0.104,0.102,0.095,0.083,0.09,0.095
4,8,2023,12540,"110000-813000, 920000",NaN,1,01-000000,"Total, All Industries",263700.000,260600.000,...,358700.000,359200.000,353000.000,345400.000,344000.000,335700.000,339700.000,351000.000,351900.00,348000.000

In [3]:
KernCounty.drop(['SORTORDER', 'BMYEAR', 'AREA', 'INCLUDES', 'BREAKS', 'PNCO', 'SS-NAICS'], axis=1, inplace=True)

In [4]:
KernCounty.head()

,TITLE,2010-01-01 00:00:00,2010-02-01 00:00:00,2010-03-01 00:00:00,2010-04-01 00:00:00,2010-05-01 00:00:00,2010-06-01 00:00:00,2010-07-01 00:00:00,2010-08-01 00:00:00,2010-09-01 00:00:00,...,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00
0,Civilian Labor Force,368200.000,367500.000,366600.00,369500.000,371600.000,375500.000,371200.00,376400.000,376000.000,...,398200.000,400100.000,395400.000,399100.000,400100.000,391900.000,388500.000,391500.000,390400.00,391700.000
1,Civilian Employment,304900.000,302400.000,300500.00,309100.000,313500.000,317000.000,311800.00,319700.000,321400.000,...,367000.000,368400.000,361100.000,361100.000,358600.000,352000.000,351600.000,359000.000,355100.00,354700.000
2,Civilian Unemployment,63300.000,65100.000,66100.00,60400.000,58100.000,58500.000,59500.00,56800.000,54500.000,...,31200.000,31700.000,34300.000,38000.000,41500.000,39900.000,37000.000,32500.000,35300.00,37100.000
3,Civilian Unemployment Rate,0.172,0.177,0.18,0.163,0.156,0.156,0.16,0.151,0.145,...,0.078,0.079,0.087,0.095,0.104,0.102,0.095,0.083,0.09,0.095
4,"Total, All Industries",263700.000,260600.000,258600.00,268800.000,276700.000,283700.000,273700.00,281200.000,284000.000,...,358700.000,359200.000,353000.000,345400.000,344000.000,335700.000,339700.000,351000.000,351900.00,348000.000

In [5]:
titles_df = KernCounty["TITLE"]
titles_df

0                                  Civilian Labor Force
1                                   Civilian Employment
2                                 Civilian Unemployment
3                            Civilian Unemployment Rate
4                                 Total, All Industries
5                                            Total Farm
6                                         Total Nonfarm
7                                         Total Private
8                                       Goods Producing
9                     Mining, Logging, and Construction
10                                   Mining and Logging
11                                         Construction
12                                        Manufacturing
13                                        Durable Goods
14                                    Non-Durable Goods
15                                   Food Manufacturing
16                                    Service-Providing
17                            Private Service Providing
18                 Trade, Transportation, and Utilities
19                                      Wholesale Trade
20                                         Retail Trade
21                          Food and Beverage Retailers
22                        General Merchandise Retailers
23                                    Department Stores
24              Clothing, Clothing Accessories, Shoe...
25            Transportation, Warehousing, and Utili...
26                                          Information
27                                 Financial Activities
28                                Finance and Insurance
29                   Real Estate and Rental and Leasing
30                   Professional and Business Services
31            Professional, Scientific, and Technica...
32              Management of Companies and Enterprises
33            Administrative and Support and Waste a...
34                Private Education and Health Services
35                         Private Educational Services
36                    Health Care and Social Assistance
37                      Ambulatory Health Care Services
38                                            Hospitals
39                              Leisure and Hospitality
40                  Arts, Entertainment, and Recreation
41                      Accommodation and Food Services
42                    Food Services and Drinking Places
43                  Restaurants and Other Eating Places
44                                       Other Services
45                                           Government
46                                   Federal Government
47                                Department of Defense
48              Federal Government excluding Departm...
49                     Total State and Local Government
50                                     State Government
51                State Government Educational Services
52                 State Government Excluding Education
53                                     Local Government
54                Local Government Educational Services
55            Local Government excluding Educational...
56                                    County Government
57                                      City Government
58                        Special Districts plus Tribes
Name: TITLE, dtype: object

In [6]:
KernCounty.head()

,TITLE,2010-01-01 00:00:00,2010-02-01 00:00:00,2010-03-01 00:00:00,2010-04-01 00:00:00,2010-05-01 00:00:00,2010-06-01 00:00:00,2010-07-01 00:00:00,2010-08-01 00:00:00,2010-09-01 00:00:00,...,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00
0,Civilian Labor Force,368200.000,367500.000,366600.00,369500.000,371600.000,375500.000,371200.00,376400.000,376000.000,...,398200.000,400100.000,395400.000,399100.000,400100.000,391900.000,388500.000,391500.000,390400.00,391700.000
1,Civilian Employment,304900.000,302400.000,300500.00,309100.000,313500.000,317000.000,311800.00,319700.000,321400.000,...,367000.000,368400.000,361100.000,361100.000,358600.000,352000.000,351600.000,359000.000,355100.00,354700.000
2,Civilian Unemployment,63300.000,65100.000,66100.00,60400.000,58100.000,58500.000,59500.00,56800.000,54500.000,...,31200.000,31700.000,34300.000,38000.000,41500.000,39900.000,37000.000,32500.000,35300.00,37100.000
3,Civilian Unemployment Rate,0.172,0.177,0.18,0.163,0.156,0.156,0.16,0.151,0.145,...,0.078,0.079,0.087,0.095,0.104,0.102,0.095,0.083,0.09,0.095
4,"Total, All Industries",263700.000,260600.000,258600.00,268800.000,276700.000,283700.000,273700.00,281200.000,284000.000,...,358700.000,359200.000,353000.000,345400.000,344000.000,335700.000,339700.000,351000.000,351900.00,348000.000

In [7]:
KernCounty.count

<bound method DataFrame.count of                                                 TITLE  2010-01-01 00:00:00  \
0                                Civilian Labor Force           368200.000
1                                 Civilian Employment           304900.000
2                               Civilian Unemployment            63300.000
3                          Civilian Unemployment Rate                0.172
4                               Total, All Industries           263700.000
5                                          Total Farm            38000.000
6                                       Total Nonfarm           225700.000
7                                       Total Private           165500.000
8                                     Goods Producing            34000.000
9                   Mining, Logging, and Construction            21300.000
10                                 Mining and Logging             9100.000
11                                       Construction            12200.000
12                                      Manufacturing            12700.000
13                                      Durable Goods             5000.000
14                                  Non-Durable Goods             7700.000
15                                 Food Manufacturing             5400.000
16                                  Service-Providing           191700.000
17                          Private Service Providing           131500.000
18               Trade, Transportation, and Utilities            41700.000
19                                    Wholesale Trade             7000.000
20                                       Retail Trade            26000.000
21                        Food and Beverage Retailers             5500.000
22                      General Merchandise Retailers             5600.000
23                                  Department Stores             2500.000
24            Clothing, Clothing Accessories, Shoe...             2200.000
25          Transportation, Warehousing, and Utili...             8700.000
26                                        Information             2700.000
27                               Financial Activities             7800.000
28                              Finance and Insurance             4800.000
29                 Real Estate and Rental and Leasing             3000.000
30                 Professional and Business Services            23700.000
31          Professional, Scientific, and Technica...            10200.000
32            Management of Companies and Enterprises             2900.000
33          Administrative and Support and Waste a...            10600.000
34              Private Education and Health Services            29200.000
35                       Private Educational Services             1700.000
36                  Health Care and Social Assistance            27500.000
37                    Ambulatory Health Care Services            10400.000
38                                          Hospitals             6300.000
39                            Leisure and Hospitality            19800.000
40                Arts, Entertainment, and Recreation             2200.000
41                    Accommodation and Food Services            17600.000
42                  Food Services and Drinking Places            15900.000
43                Restaurants and Other Eating Places            15400.000
44                                     Other Services             6600.000
45                                         Government            60200.000
46                                 Federal Government            10500.000
47                              Department of Defense             7600.000
48            Federal Government excluding Departm...             2900.000
49                   Total State and Local Government            49700.000
50                                   State Government             9800.000
51              State Government Educational Services             1200.000
52               State Government Excluding Education             8600.000
53                                   Local Government            39900.000
54              Local Government Educational Services            25500.000
55          Local Government excluding Educational...            14400.000
56                                  County Government             9600.000
57                                    City Government             2600.000
58                      Special Districts plus Tribes             2200.000

    2010-02-01 00:00:00  2010-03-01 00:00:00  2010-04-01 00:00:00  \
0            367500.000            366600.00           369500.000
1            302400.000            300500.00           309100.000
2             65100.000             66100.00            60400.000
3                 0.177                 0.18                0.163
4            260600.000            258600.00           268800.000
5             34800.000             30200.00            35800.000
6            225800.000            228400.00           233000.000
7            164900.000            165900.00           168800.000
8             33400.000             33900.00            34700.000
9             20800.000             21200.00            21800.000
10             8700.000              8800.00             9200.000
11            12100.000             12400.00            12600.000
12            12600.000             12700.00            12900.000
13             5000.000              5000.00             5000.000
14             7600.000              7700.00             7900.000
15             5400.000              5400.00             5400.000
16           192400.000            194500.00           198300.000
17           131500.000            132000.00           134100.000
18            41500.000             41300.00            41800.000
19             6900.000              6600.00             7100.000
20            25900.000             26000.00            26000.000
21             5500.000              5600.00             5600.000
22             5600.000              5700.00             5500.000
23             2300.000              2300.00             2300.000
24             2100.000              2100.00             2100.000
25             8700.000              8700.00             8700.000
26             2600.000              2600.00             2600.000
27             7900.000              7900.00             8000.000
28             4800.000              4800.00             4800.000
29             3100.000              3100.00             3200.000
30            23400.000             23700.00            24600.000
31            10100.000             10000.00            10600.000
32             2800.000              2900.00             3000.000
33            10500.000             10800.00            11000.000
34            29300.000             29400.00            29500.000
35             1800.000              1700.00             1600.000
36            27500.000             27700.00            27900.000
37            10400.000             10400.00            10500.000
38             6300.000              6400.00             6400.000
39            20100.000             20300.00            20800.000
40             2300.000              2300.00             2400.000
41            17800.000             18000.00            18400.000
42            16100.000             16400.00            16700.000
43            15600.000             15800.00            16000.000
44             6700.000              6800.00             6800.000
45            60900.000             62500.00            64200.000
46            10500.000             10500.00            11100.000
47             7600.000              7600.00             7700.000
48             2900.000              2900.00             3400.000
49            50400.000             52000.00            53100.000
50             9900.000              9900.00             9900.000
51             1300.000              1300.00             1300.000
52             8600.000              8600.00             8600.000
53            40500.000             42100.00            43200.000
54            26200.000             27700.00            28800.000
55            14300.000             14400.00            14400.000
56             9600.000              9600.00             9600.000
57             2500.000              2500.00             2600.000
58             2300.000              2300.00             2100.000

    2010-05-01 00:00:00  2010-06-01 00:00:00  2010-07-01 00:00:00  \
0            371600.000           375500.000            371200.00
1            313500.000           317000.000            311800.00
2             58100.000            58500.000             59500.00
3                 0.156                0.156                 0.16
4            276700.000           283700.000            273700.00
5             43600.000            50400.000             49900.00
6            233100.000           233300.000            223800.00
7            169000.000           169800.000            170400.00
8             35400.000            35600.000             36100.00
9             22600.000            22800.000             23100.00
10             9900.000             9900.000             10200.00
11            12700.000            12900.000             12900.00
12            12800.000            12800.000             13000.00
13             5000.000             5000.000              5100.00
14             7800.000             7800.000              7900.00
15             5400.000             5400.000              5400.00
16           197700.000           197700.000            187700.00
17           133600.000           134200.000            134300.00
18            41900.000            41900.000             42800.00
19             7100.000             7500.000              8400.00
20            25800.000            25600.000             25500.00
21             5600.000             5600.000              5500.00
22             5400.000             5300.000              5200.00
23             2200.000             2200.000              2100.00
24             2100.000             2100.000              2200.00
25             9000.000             8800.000              8900.00
26             2600.000             2600.000              2900.00
27             8000.000             7900.000              7900.00
28             4800.000             4800.000              4800.00
29             3200.000             3100.000              3100.00
30            24300.000            24600.000             23900.00
31            10200.000            10200.000             10100.00
32             3000.000             3100.000              3100.00
33            11100.000            11300.000             10700.00
34            29300.000            29400.000             29600.00
35             1500.000             1600.000              1500.00
36            27800.000            27800.000             28100.00
37            10600.000            10600.000             10600.00
38             6400.000             6400.000              6500.00
39            20800.000            21100.000             20800.00
40             2500.000             2500.000              2400.00
41            18300.000            18600.000             18400.00
42            16600.000            16800.000             16600.00
43            16000.000            16300.000             16100.00
44             6700.000             6700.000              6400.00
45            64100.000            63500.000             53400.00
46            11700.000            11400.000             11200.00
47             7700.000             7800.000              7900.00
48             4000.000             3600.000              3300.00
49            52400.000            52100.000             42200.00
50             9900.000             9900.000              9900.00
51             1300.000             1300.000              1300.00
52             8600.000             8600.000              8600.00
53            42500.000            42200.000             32300.00
54            28200.000            27600.000             18100.00
55            14300.000            14600.000             14200.00
56             9600.000             9500.000              9200.00
57             2700.000             2800.000              2800.00
58             2100.000             2300.000              2300.00

    2010-08-01 00:00:00  2010-09-01 00:00:00  ...  2023-10-01 00:00:00  \
0            376400.000           376000.000  ...           398200.000
1            319700.000           321400.000  ...           367000.000
2             56800.000            54500.000  ...            31200.000
3                 0.151                0.145  ...                0.078
4            281200.000           284000.000  ...           358700.000
5             54400.000            54300.000  ...            65200.000
6            226800.000           229700.000  ...           293500.000
7            171000.000           170900.000  ...           222200.000
8             36300.000            36700.000  ...            36500.000
9             23300.000            23200.000  ...            23900.000
10            10300.000            10400.000  ...             7600.000
11            13000.000            12800.000  ...            16300.000
12            13000.000            13500.000  ...            12600.000
13             5000.000             5100.000  ...             5000.000
14             8000.000             8400.000  ...             7600.000
15             5500.000             5900.000  ...             4600.000
16           190500.000           193000.000  ...           257000.000
17           134700.000           134200.000  ...           185700.000
18            43200.000            43000.000  ...            61900.000
19             8600.000             8600.000  ...             8300.000
20            25600.000            25500.000  ...            32700.000
21             5600.000             5700.000  ...             7000.000
22             5200.000             5300.000  ...             7700.000
23             2200.000             2100.000  ...             1700.000
24             2200.000             2100.000  ...             2300.000
25             9000.000             8900.000  ...            20900.000
26             2800.000             2700.000  ...             1700.000
27             7800.000             7700.000  ...             7600.000
28             4800.000             4700.000  ...             4100.000
29             3000.000             3000.000  ...             3500.000
30            23900.000            23900.000  ...            27400.000
31            10200.000            10100.000  ...            11400.000
32             3100.000             3100.000  ...             2700.000
33            10600.000            10700.000  ...            13300.000
34            29800.000            29600.000  ...            48300.000
35             1500.000             1400.000  ...             2100.000
36            28300.000            28200.000  ...            46200.000
37            10500.000            10600.000  ...            16700.000
38             6600.000             6500.000  ...             8100.000
39            20600.000            20700.000  ...            29700.000
40             2300.000             2300.000  ...             2600.000
41            18300.000            18400.000  ...            27100.000
42            16600.000            16600.000  ...            25200.000
43            16000.000            16100.000  ...            24300.000
44             6600.000             6600.000  ...             9100.000
45            55800.000            58800.000  ...            71300.000
46            10900.000            10700.000  ...            11100.000
47             7900.000             7800.000  ...             8300.000
48             3000.000             2900.000  ...             2800.000
49            44900.000            48100.000  ...            60200.000
50             9800.000             9700.000  ...             9600.000
51             1200.000             1100.000  ...             1800.000
52             8600.000             8600.000  ...             7800.000
53            35100.000            38400.000  ...            50600.000
54            21100.000            24500.000  ...            34200.000
55            14000.000            13900.000  ...            16400.000
56             9100.000             9100.000  ...            11100.000
57             2700.000             2600.000  ...             3000.000
58             2200.000             2100.000  ...             2300.000

    2023-11-01 00:00:00  2023-12-01 00:00:00  2024-01-01 00:00:00  \
0            400100.000           395400.000           399100.000
1            368400.000           361100.000           361100.000
2             31700.000            34300.000            38000.000
3                 0.079                0.087                0.095
4            359200.000           353000.000           345400.000
5             64100.000            56200.000            54800.000
6            295100.000           296800.000           290600.000
7            222700.000           223400.000           219200.000
8             36300.000            36400.000            35800.000
9             23800.000            23900.000            23300.000
10             7600.000             7600.000             7600.000
11            16200.000            16300.000            15700.000
12            12500.000            12500.000            12500.000
13             5000.000             5000.000             5000.000
14             7500.000             7500.000             7500.000
15             4600.000             4600.000             4700.000
16           258800.000           260400.000           254800.000
17           186400.000           187000.000           183400.000
18            62500.000            62800.000            60300.000
19             8300.000             8300.000             8300.000
20            33200.000            33500.000            31700.000
21             7100.000             7000.000             6900.000
22             7900.000             8000.000             7300.000
23             1800.000             1800.000             1500.000
24             2500.000             2600.000             2200.000
25            21000.000            21000.000            20300.000
26             1700.000             1700.000             1700.000
27             7600.000             7600.000             7600.000
28             4100.000             4100.000             4100.000
29             3500.000             3500.000             3500.000
30            27400.000            27500.000            27200.000
31            11400.000            11700.000            11700.000
32             2800.000             2800.000             2700.000
33            13200.000            13000.000            12800.000
34            48500.000            48800.000            48700.000
35             2200.000             2200.000             2100.000
36            46300.000            46600.000            46600.000
37            16700.000            16800.000            16700.000
38             8200.000             8200.000             8200.000
39            29700.000            29600.000            29000.000
40             2600.000             2600.000             2600.000
41            27100.000            27000.000            26400.000
42            25200.000            25000.000            24500.000
43            24400.000            24100.000            23600.000
44             9000.000             9000.000             8900.000
45            72400.000            73400.000            71400.000
46            11100.000            11200.000            11100.000
47             8300.000             8300.000             8400.000

In [8]:
# Assuming your DataFrame is called df
columns_2010 = KernCounty.iloc[:, 1:13]  # Select the columns for 2010

# Calculate the row-wise average for these columns and round to 2 decimal places
KernCounty['2010_Average'] = columns_2010.mean(axis=1).round(2)

# Print the resulting DataFrame with the new '2010_Average' column
print(KernCounty[['TITLE', '2010_Average']])

                                                TITLE  2010_Average
0                                Civilian Labor Force     372241.67
1                                 Civilian Employment     312575.00
2                               Civilian Unemployment      59675.00
3                          Civilian Unemployment Rate          0.16
4                               Total, All Industries     274383.33
5                                          Total Farm      44575.00
6                                       Total Nonfarm     229808.33
7                                       Total Private     169175.00
8                                     Goods Producing      35541.67
9                   Mining, Logging, and Construction      22541.67
10                                 Mining and Logging       9825.00
11                                       Construction      12716.67
12                                      Manufacturing      13000.00
13                                      Durable Goods       5033.33
14                                  Non-Durable Goods       7966.67
15                                 Food Manufacturing       5541.67
16                                  Service-Providing     194266.67
17                          Private Service Providing     133633.33
18               Trade, Transportation, and Utilities      42308.33
19                                    Wholesale Trade       7458.33
20                                       Retail Trade      26008.33
21                        Food and Beverage Retailers       5641.67
22                      General Merchandise Retailers       5508.33
23                                  Department Stores       2241.67
24            Clothing, Clothing Accessories, Shoe...       2216.67
25          Transportation, Warehousing, and Utili...       8841.67
26                                        Information       2691.67
27                               Financial Activities       7791.67
28                              Finance and Insurance       4741.67
29                 Real Estate and Rental and Leasing       3050.00
30                 Professional and Business Services      24166.67
31          Professional, Scientific, and Technica...      10200.00
32            Management of Companies and Enterprises       3100.00
33          Administrative and Support and Waste a...      10866.67
34              Private Education and Health Services      29558.33
35                       Private Educational Services       1558.33
36                  Health Care and Social Assistance      28000.00
37                    Ambulatory Health Care Services      10558.33
38                                          Hospitals       6450.00
39                            Leisure and Hospitality      20491.67
40                Arts, Entertainment, and Recreation       2308.33
41                    Accommodation and Food Services      18183.33
42                  Food Services and Drinking Places      16466.67
43                Restaurants and Other Eating Places      15933.33
44                                     Other Services       6625.00
45                                         Government      60633.33
46                                 Federal Government      10875.00
47                              Department of Defense       7758.33
48            Federal Government excluding Departm...       3116.67
49                   Total State and Local Government      49758.33
50                                   State Government       9833.33
51              State Government Educational Services       1250.00
52               State Government Excluding Education       8583.33
53                                   Local Government      39925.00
54              Local Government Educational Services      25766.67
55          Local Government excluding Educational...      14158.33
56                                  County Government       9333.33
57                                    City Government       2633.33
58                      Special Districts plus Tribes       2208.33

In [10]:
# Create an empty DataFrame to store the averages for each year
averaged_years_df = pd.DataFrame()

# Loop through each year from 2010 to 2024
for year in range(2010, 2025):
    # Adjust the column range based on your DataFrame structure
    # Replace '1:13' with the actual column range for each year
    start_col = (year - 2010) * 12 + 1  # Adjust column index logic as per your DataFrame structure
    end_col = start_col + 12
    
    # Select the columns for the current year
    columns_for_year = KernCounty.iloc[:, start_col:end_col]
    
    # Calculate the row-wise average for these columns and round to 2 decimal places
    KernCounty[f'{year}_Average'] = columns_for_year.mean(axis=1).round(2)
    
    # Add the year and its average column to the new DataFrame
    averaged_years_df[f'{year}_Average'] = KernCounty[f'{year}_Average']

# Add the 'TITLE' column to the new DataFrame
averaged_years_df['TITLE'] = KernCounty['TITLE']

# Reorder columns to put 'TITLE' at the front
averaged_years_df = averaged_years_df[['TITLE'] + [col for col in averaged_years_df.columns if col != 'TITLE']]

# Print or inspect the new DataFrame with averages from 2010 to 2024 and the TITLE column
print(averaged_years_df)

                                                TITLE  2010_Average  \
0                                Civilian Labor Force     372241.67
1                                 Civilian Employment     312575.00
2                               Civilian Unemployment      59675.00
3                          Civilian Unemployment Rate          0.16
4                               Total, All Industries     274383.33
5                                          Total Farm      44575.00
6                                       Total Nonfarm     229808.33
7                                       Total Private     169175.00
8                                     Goods Producing      35541.67
9                   Mining, Logging, and Construction      22541.67
10                                 Mining and Logging       9825.00
11                                       Construction      12716.67
12                                      Manufacturing      13000.00
13                                      Durable Goods       5033.33
14                                  Non-Durable Goods       7966.67
15                                 Food Manufacturing       5541.67
16                                  Service-Providing     194266.67
17                          Private Service Providing     133633.33
18               Trade, Transportation, and Utilities      42308.33
19                                    Wholesale Trade       7458.33
20                                       Retail Trade      26008.33
21                        Food and Beverage Retailers       5641.67
22                      General Merchandise Retailers       5508.33
23                                  Department Stores       2241.67
24            Clothing, Clothing Accessories, Shoe...       2216.67
25          Transportation, Warehousing, and Utili...       8841.67
26                                        Information       2691.67
27                               Financial Activities       7791.67
28                              Finance and Insurance       4741.67
29                 Real Estate and Rental and Leasing       3050.00
30                 Professional and Business Services      24166.67
31          Professional, Scientific, and Technica...      10200.00
32            Management of Companies and Enterprises       3100.00
33          Administrative and Support and Waste a...      10866.67
34              Private Education and Health Services      29558.33
35                       Private Educational Services       1558.33
36                  Health Care and Social Assistance      28000.00
37                    Ambulatory Health Care Services      10558.33
38                                          Hospitals       6450.00
39                            Leisure and Hospitality      20491.67
40                Arts, Entertainment, and Recreation       2308.33
41                    Accommodation and Food Services      18183.33
42                  Food Services and Drinking Places      16466.67
43                Restaurants and Other Eating Places      15933.33
44                                     Other Services       6625.00
45                                         Government      60633.33
46                                 Federal Government      10875.00
47                              Department of Defense       7758.33
48            Federal Government excluding Departm...       3116.67
49                   Total State and Local Government      49758.33
50                                   State Government       9833.33
51              State Government Educational Services       1250.00
52               State Government Excluding Education       8583.33
53                                   Local Government      39925.00
54              Local Government Educational Services      25766.67
55          Local Government excluding Educational...      14158.33
56                                  County Government       9333.33
57                                    City Government       2633.33
58                      Special Districts plus Tribes       2208.33

    2011_Average  2012_Average  2013_Average  2014_Average  2015_Average  \
0      382025.00     391266.67     392208.33     391908.33     390158.33
1      324441.67     339000.00     345558.33     350625.00     350050.00
2       57591.67      52266.67      46641.67      41275.00      40091.67
3           0.15          0.13          0.12          0.11          0.10
4      284750.00     299283.33     309158.33     315633.33     315900.00
5       48216.67      53758.33      59150.00      59816.67      58808.33
6      236533.33     245525.00     250008.33     255816.67     257091.67
7      176383.33     186741.67     191566.67     196125.00     195583.33
8       38675.00      43016.67      43816.67      45650.00      42041.67
9       25575.00      29541.67      29758.33      31075.00      27891.67
10      11608.33      12841.67      12508.33      12900.00      11408.33
11      13966.67      16700.00      17250.00      18175.00      16483.33
12      13100.00      13475.00      14058.33      14575.00      14150.00
13       5058.33       5133.33       5358.33       5641.67       5283.33
14       8041.67       8341.67       8700.00       8933.33       8866.67
15       5533.33       5833.33       6066.67       6050.00       5916.67
16     197858.33     202508.33     206191.67     210166.67     215050.00
17     137708.33     143725.00     147750.00     150475.00     153541.67
18      43791.67      45391.67      47516.67      49433.33      50716.67
19       7591.67       7758.33       8475.00       8675.00       8341.67
20      27075.00      27925.00      28941.67      30300.00      31466.67
21       6058.33       5958.33       6066.67       6383.33       6616.67
22       5633.33       5800.00       6033.33       6283.33       6833.33
23       2116.67       2108.33       2033.33       2050.00       2150.00
24       2358.33       2375.00       2491.67       2941.67       3325.00
25       9125.00       9708.33      10100.00      10458.33      10908.33
26       2616.67       2675.00       2541.67       2383.33       2683.33
27       7883.33       8316.67       8383.33       8233.33       8091.67
28       4866.67       5083.33       5100.00       5016.67       4925.00
29       3016.67       3233.33       3283.33       3216.67       3166.67
30      25783.33      27041.67      26758.33      26383.33      25891.67
31      10733.33      11316.67      11125.00      10833.33      10166.67
32       3425.00       3475.00       3441.67       3466.67       3216.67
33      11625.00      12250.00      12191.67      12083.33      12508.33
34      30133.33      31450.00      32266.67      32575.00      33433.33
35       1575.00       1633.33       1508.33       1450.00       1400.00
36      28558.33      29816.67      30758.33      31125.00      32033.33
37      10733.33      11200.00      11683.33      12100.00      12416.67
38       6808.33       7175.00       7166.67       7116.67       7408.33
39      20716.67      21633.33      22800.00      23691.67      25041.67
40       2316.67       2366.67       2391.67       2300.00       2391.67
41      18400.00      19266.67      20408.33      21391.67      22650.00
42      16675.00      17525.00      18625.00      19675.00      20775.00
43      16158.33      16958.33      18033.33      19033.33      20100.00
44       6783.33       7216.67       7483.33       7775.00       7683.33
45      60150.00      58783.33      58441.67      59691.67      61508.33
46      10658.33      10383.33      10008.33       9633.33       9883.33
47       7825.00       7633.33       7441.67       7175.00       7416.67
48       2833.33       2750.00       2566.67       2458.33       2466.67
49      49491.67      48400.00      48433.33      50058.33      51625.00
50       9725.00       9391.67       8841.67       9241.67       9575.00
51       1241.67       1316.67       1316.67       1391.67       1450.00
52       8483.33       8075.00       7525.00       7850.00       8125.00
53      39766.67      39008.33      39591.67      40816.67      42050.00
54      26108.33      25808.33      25841.67      26708.33      27616.67
55      13658.33      13200.00      13750.00      14108.33      14433.33
56       8900.00       8633.33       8983.33       9041.67       9308.33
57       2541.67       2391.67       2416.67       2691.67       2758.33
58       2200.00       2175.00       2350.00       2375.00       2366.67

    2016_Average  2017_Average  2018_Average  2019_Average  2020_Average  \
0      388108.33     384083.33     385733.33     388175.00     386358.33
1      347708.33     348516.67     354566.67     357725.00     336841.67
2       40416.67      35583.33      31166.67      30441.67      49525.00
3           0.10          0.09          0.08          0.08          0.13
4      317616.67     320175.00     327900.00     335158.33     319291.67
5       62125.00      61375.00      61491.67      62133.33      58366.67
6      255491.67     258800.00     266408.33     273025.00     260925.00
7      191691.67     193566.67     200341.67     205416.67     195400.00
8       37066.67      36950.00      38400.00      38800.00      35700.00
9       23525.00      23558.33      25233.33      25875.00      23375.00
10       8983.33       8616.67       9308.33       9558.33       7950.00
11      14541.67      14941.67      15925.00      16316.67      15425.00
12      13541.67      13391.67      13166.67      12925.00      12325.00
13       4791.67       4766.67       4800.00       4891.67       4733.33
14       8750.00       8625.00       8366.67       8033.33       7591.67
15       5908.33       5883.33       5650.00       5183.33       4841.67
16     218425.00     221850.00     228008.33     234225.00     225225.00
17     154625.00     156616.67     161941.67     166616.67     159700.00
18      51141.67      51633.33      53291.67      52858.33      52791.67
19       8108.33       8225.00       8250.00       8033.33       7525.00
20      32075.00      31958.33      31808.33      31133.33      30100.00
21       6783.33       6508.33       6425.00       6425.00       6575.00
22       6766.67       6966.67       6983.33       6916.67       7041.67
23       2025.00       1950.00       1900.00       1675.00       1466.67
24       3133.33       2858.33       2808.33       2500.00       1691.67
25      10958.33      11450.00      13233.33      13691.67      15166.67
26       2166.67       2033.33       2033.33       1908.33       1525.00
27       7916.67       7825.00       7766.67       7725.00       7533.33
28       4800.00       4800.00       4650.00       4500.00       4408.33
29       3116.67       3025.00       3116.67       3225.00       3125.00
30      25500.00      25108.33      26133.33      27366.67      26441.67
31       9450.00       9283.33       9450.00       9783.33      10375.00
32       3191.67       2975.00       2791.67       2658.33       2500.00
33      12858.33      12850.00      13891.67      14925.00      13566.67
34      34783.33      36433.33      38091.67      40925.00      40800.00
35       1450.00       1491.67       1666.67       1825.00       1550.00
36      33333.33      34941.67      36425.00      39100.00      39250.00
37      12758.33      13225.00      13666.67      14833.33      14525.00
38       7883.33       8200.00       8216.67       8250.00       8091.67
39      25458.33      25858.33      26708.33      27558.33      23216.67
40       2616.67       2500.00       2475.00       2625.00       1575.00
41      22841.67      23358.33      24233.33      24933.33      21641.67
42      20866.67      21383.33      22250.00      23025.00      20066.67
43      20083.33      20525.00      21433.33      22233.33      19550.00
44       7658.33       7725.00       7916.67       8275.00       7391.67
45      63800.00      65233.33      66066.67      67608.33      65525.00
46      10208.33      10441.67      10566.67      10908.33      11325.00
47       7700.00       7875.00       7983.33       8258.33       8541.67
48       2508.33       2566.67       2583.33       2650.00       2783.33
49      53591.67      54791.67      55500.00      56700.00      54200.00
50       9891.67      10083.33      10241.67      10216.67      10191.67
51       1575.00       1741.67       1841.67       1758.33       1758.33
52       8316.67       8341.67       8400.00       8458.33       8433.33
53      43700.00      44708.33      45258.33      46483.33      44008.33
54      29016.67      30008.33      30366.67      31116.67      28933.33
55      14683.33      14700.00      14891.67      15366.67      15075.00
56       9483.33       9641.67       9841.67      10158.33      10158.33
57       2766.67       2758.33       2800.00       2841.67       2775.00
58       2433.33       2300.00       2250.00       2366.67       2141.67

    2021_Average  2022_Average  2023_Average  2024_Average
0      384991.67     389175.00     393733.33     390237.50
1      346783.33     361725.00     360966.67     347025.00
2       38200.00      27441.67      32758.33      43229.17
3           0.10          0.07          0.08          0.11
4      331441.67     346583.33     346616.67     324909.03
5       60575.00      60350.00      56058.33      53576.39
6      270866.67     286233.33     290558.33     271332.64
7      206066.67     218983.33     220775.00     205107.64
8       35141.67      36975.00      36508.33      38141.67
9       22941.67      24475.00      24075.00      25207.64
10       7441.67       7800.00       7800.00       9423.61
11      15500.00      16675.00      16275.00      15784.03
12      12200.00      12500.00      12433.33      12934.03
13       4775.00       4891.67       5000.00       5093.75
14       7425.00       7608.33       7433.33       7840.28
15       4658.33       4733.33       4558.33       5118.75
16     235725.00     249258.33     254050.00     233190.97
17     170925.00     182008.33     184266.67     166965.97
18      59700.00      63191.67      61608.33      54111.81
19       7716.67       8166.67       8400.00       8171.53
20      32266.67      32916.67      32433.33      30154.17
21       6783.33       6925.00       6958.33       6517.36
22       7683.33       7708.33       7525.00       6671.53
23       1625.00       1675.00       1641.67       1720.83
24       2241.67       2408.33       2316.67       2265.28
25      19716.67      22108.33      20775.00      15786.11
26       1541.67       1625.00       1708.33       2067.36
27       7641.67       7583.33       7525.00       7792.36
28       4425.00       4191.67       4100.00       4450.70
29       3216.67       3391.67       3425.00       3341.67
30      26008.33      27041.67      26991.67      26936.11
31      10350.00      11533.33      11483.33      11450.69
32       2650.00       2658.33       2725.00       3000.70
33      13008.33      12850.00      12783.33      12484.72
34      41633.33      44333.33      47525.00      41490.28
35       1800.00       1933.33       2083.33       1918.75
36      39833.33      42400.00      45441.67      39571.53
37      14758.33      15433.33      16283.33      14497.92
38       7783.33       7966.67       8058.33       7718.06
39      26508.33      29425.00      29933.33      26277.78
40       1908.33       2483.33       2591.67       2531.94
41      24600.00      26941.67      27341.67      23745.83
42      22983.33      25183.33      25483.33      21872.22
43      22308.33      24325.00      24541.67      21151.39
44       7891.67       8808.33       8975.00       8290.28
45      64800.00      67250.00      69783.33      66225.00
46      11250.00      10950.00      11033.33      10796.53
47       8616.67       8308.33       8266.67       8019.44
48       2633.33       2641.67       2766.67       2777.08
49      53550.00      56300.00      58750.00      55428.47
50       9841.67       9783.33       9750.00       9436.11
51       1591.67       1683.33       1758.33       1576.39
52       8250.00       8100.00       7991.67       7859.72
53      43708.33      46516.67      49000.00      45992.36
54      28975.00      31583.33      33216.67      30736.11
55      14733.33      14933.33      15783.33      15256.25
56      10000.00      10058.33      10608.33      10032.64
57       2650.00       2716.67       2916.67       2864.58
58       2083.33       2158.33       2258.33       2359.03

In [11]:
averaged_years_df.head()

,TITLE,2010_Average,2011_Average,2012_Average,2013_Average,2014_Average,2015_Average,2016_Average,2017_Average,2018_Average,2019_Average,2020_Average,2021_Average,2022_Average,2023_Average,2024_Average
0,Civilian Labor Force,372241.67,382025.00,391266.67,392208.33,391908.33,390158.33,388108.33,384083.33,385733.33,388175.00,386358.33,384991.67,389175.00,393733.33,390237.50
1,Civilian Employment,312575.00,324441.67,339000.00,345558.33,350625.00,350050.00,347708.33,348516.67,354566.67,357725.00,336841.67,346783.33,361725.00,360966.67,347025.00
2,Civilian Unemployment,59675.00,57591.67,52266.67,46641.67,41275.00,40091.67,40416.67,35583.33,31166.67,30441.67,49525.00,38200.00,27441.67,32758.33,43229.17
3,Civilian Unemployment Rate,0.16,0.15,0.13,0.12,0.11,0.10,0.10,0.09,0.08,0.08,0.13,0.10,0.07,0.08,0.11
4,"Total, All Industries",274383.33,284750.00,299283.33,309158.33,315633.33,315900.00,317616.67,320175.00,327900.00,335158.33,319291.67,331441.67,346583.33,346616.67,324909.03

In [12]:
# Export the DataFrame to a CSV file
averaged_years_df.to_csv('Kern_county.csv', index=False)  # Set index=False to avoid exporting the row indices