In [1]:
import pandas as pd

In [2]:
avg_cost_by_county = pd.read_csv('../data/avg_cost_by_county.csv')

In [3]:
avg_cost_by_county.head()

,RegionID,SizeRank,RegionName,State,1/31/2004,2/29/2004,3/31/2004,4/30/2004,5/31/2004,6/30/2004,...,10/31/2023,11/30/2023,12/31/2023,1/31/2024,2/29/2024,3/31/2024,4/30/2024,5/31/2024,6/30/2024,7/31/2024
0,3101,0,Los Angeles County,CA,359637.887854,365587.644879,371964.449058,379899.180522,389740.328886,399902.550401,...,869954.975653,878067.742426,883097.441686,882055.961553,877150.390199,873255.631790,873908.269833,877153.822292,879295.516241,883035.966550
1,139,1,Cook County,IL,212183.381348,213545.681301,214699.864000,216016.957799,217640.336495,219517.627537,...,300775.020143,301699.133374,302164.120803,302402.124218,303366.204744,305426.677900,308133.807900,310009.520838,311088.578500,311761.624093
2,1090,2,Harris County,TX,121818.012379,122617.363618,124111.219107,125504.882549,126877.064356,127403.928382,...,285303.469784,285048.636665,284752.942063,284865.744499,285335.048571,286351.917951,287410.239829,288010.555414,287890.640371,287515.312881
3,2402,3,Maricopa County,AZ,177405.207211,178222.959316,179257.984336,180538.524221,182116.180357,183826.754819,...,464980.249259,466776.161724,467741.199729,468106.891173,468648.154040,470108.251801,471891.512217,473300.598955,473470.028161,472862.524459
4,2841,4,San Diego County,CA,398657.715678,404627.790326,413281.930706,421490.824884,429782.054434,442327.588370,...,902532.689606,909016.371808,912435.143858,914728.252057,919311.605890,927614.029973,937977.111708,946849.180000,951394.285382,952856.260799

In [4]:
avg_cost_by_county.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'State', '1/31/2004', '2/29/2004',
       '3/31/2004', '4/30/2004', '5/31/2004', '6/30/2004',
       ...
       '10/31/2023', '11/30/2023', '12/31/2023', '1/31/2024', '2/29/2024',
       '3/31/2024', '4/30/2024', '5/31/2024', '6/30/2024', '7/31/2024'],
      dtype='object', length=251)

In [10]:
avg_cost_2010up = pd.concat([avg_cost_by_county.iloc[:, :3], avg_cost_by_county.iloc[:, -175:]], axis=1)
avg_cost_2010up = avg_cost_2010up.drop('SizeRank', axis=1)
avg_cost_2010up.head(10)

,RegionID,RegionName,1/31/2010,2/28/2010,3/31/2010,4/30/2010,5/31/2010,6/30/2010,7/31/2010,8/31/2010,...,10/31/2023,11/30/2023,12/31/2023,1/31/2024,2/29/2024,3/31/2024,4/30/2024,5/31/2024,6/30/2024,7/31/2024
0,3101,Los Angeles County,385700.724293,386005.403754,386616.149837,388355.850762,391671.476876,391659.367453,390215.012994,386376.581887,...,8.699550e+05,8.780677e+05,8.830974e+05,8.820560e+05,8.771504e+05,8.732556e+05,8.739083e+05,8.771538e+05,8.792955e+05,8.830360e+05
1,139,Cook County,204680.935470,204431.065163,202782.526072,203166.574681,202497.131489,203182.617700,200919.652700,199148.314561,...,3.007750e+05,3.016991e+05,3.021641e+05,3.024021e+05,3.033662e+05,3.054267e+05,3.081338e+05,3.100095e+05,3.110886e+05,3.117616e+05
2,1090,Harris County,134739.406099,134655.235181,134750.277278,135152.485482,135506.156972,135443.892522,134780.625542,133545.872457,...,2.853035e+05,2.850486e+05,2.847529e+05,2.848657e+05,2.853350e+05,2.863519e+05,2.874102e+05,2.880106e+05,2.878906e+05,2.875153e+05
3,2402,Maricopa County,164934.888567,164118.409960,162833.435795,162264.122466,161654.166398,161088.220569,158876.377391,156691.051476,...,4.649802e+05,4.667762e+05,4.677412e+05,4.681069e+05,4.686482e+05,4.701083e+05,4.718915e+05,4.733006e+05,4.734700e+05,4.728625e+05
4,2841,San Diego County,364428.994052,366497.861101,368530.423442,371811.737431,373167.370697,373358.499142,371550.587320,369701.494204,...,9.025327e+05,9.090164e+05,9.124351e+05,9.147283e+05,9.193116e+05,9.276140e+05,9.379771e+05,9.468492e+05,9.513943e+05,9.528563e+05
5,1286,Orange County,482897.035720,483107.978568,482026.452846,484937.392778,486912.309221,488042.315610,485222.180413,482018.881307,...,1.084817e+06,1.096047e+06,1.103526e+06,1.107221e+06,1.109519e+06,1.116254e+06,1.128691e+06,1.143474e+06,1.153868e+06,1.161599e+06
6,581,Kings County,431377.773500,434644.415129,434827.257587,433722.561891,432027.630366,433489.838900,437174.396826,439384.093507,...,8.393059e+05,8.360185e+05,8.346801e+05,8.360716e+05,8.386273e+05,8.441612e+05,8.498112e+05,8.543086e+05,8.549174e+05,8.562879e+05
7,2964,Miami-Dade County,174854.707750,173675.809762,173156.333101,172759.371533,172301.520340,171205.477478,169809.827899,168207.589683,...,5.058970e+05,5.095889e+05,5.128376e+05,5.158341e+05,5.183549e+05,5.214210e+05,5.246271e+05,5.279603e+05,5.302239e+05,5.321994e+05
8,978,Dallas County,113323.835594,112918.018568,112418.214425,112365.633178,112272.327510,112351.718472,112053.599298,111536.017420,...,3.188779e+05,3.189365e+05,3.188323e+05,3.190313e+05,3.198591e+05,3.213421e+05,3.224285e+05,3.226811e+05,3.221589e+05,3.213848e+05
9,2832,Riverside County,207619.019850,209357.742447,210253.044919,210916.206992,212090.258813,212242.231556,211534.147016,209223.294400,...,5.904493e+05,5.930607e+05,5.953860e+05,5.973129e+05,5.994030e+05,6.020490e+05,6.049911e+05,6.079180e+05,6.096283e+05,6.110266e+05